name: I Do Concerts
favicon: null
layout_spectrum: 0.99764
typography_spectrum: 0.91273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02020b'
    - '#5d4e77'
    - '#faebf0'
    - '#b696c6'
    - '#fd0056'
  brandStrength: 0.125
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
