name: I Do Concerts
favicon: null
layout_spectrum: 0.8309722943231463
typography_spectrum: 0.3524059865158051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.031872452003881335
  lightness: 0.5390947151463479
  saturation: 0.8558703046292067
  rhythmicContrast: 0.4028895965311676
purpose: []
